### PR TITLE
Fix german gramma and spelling

### LINKED ISSUE #2: Fix German spelling or gramar mistakes
Fix any spelling or grammar mistakes in my German vocabulary. 

The German Vocab is in the `docs/german` directory.

### PR DESCRIPTION
**Pull request by 2mt-auler**
Fixes #2

### CODE REVIEW

**Comment by damcclean** [comment]
Hey, I'll merge if you delete your IDE configurations from the PR and you gitignore it :)

**Comment by Taminoful** [comment]
> Hey @2mt-auler , I'll merge if you delete your IDE configurations from the PR and you gitignore it :)

Just created a pull request for his fork which removes the `.idea` folder from the repository and adds it to the `.gitignore` file. Was solved with some git clean magic.

@2mt-auler just has to accept the pull request into his fork and it should be fine. :)

**Comment by damcclean** [comment]
Hey, thanks for doing that @Taminoful.

**Comment by damcclean** [comment]
Fixed in #4

**Pull request closed without merging**
